name: Deploy to Github Pages

on:
  push:
    branches:
      - main
      - feat/25-automate-deployment

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: ./healthchecks-front/package-lock.json

      - name: Build
        run: |
          cd healthchecks-front
          npm ci 
          npm run build
          npm run export
          cp -r out/* ..
          cd ..

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./
