name: Build and deploy to Github Pages

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]

  workflow_dispatch:

concurrency: build_and_deploy_concurrency_group

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Build
        run: |
          npm ci
          npm run export

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        if: github.ref_name == 'main'
        with:
          branch: gh-pages
          folder: ./out
          clean-exclude: ./preview

      - name: Extract PR number
        shell: bash
        run: echo "##[set-output name=pr_number;]$(echo \"$GITHUB_REF\" | awk -F / '{print $3}')"
        id: extract_pr_number

      - name: Deploy to Preview Environment
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        if: github.event_name == 'pull_request' && github.event.pull_request.action != 'closed'
        with:
          branch: gh-pages
          folder: ./out
          target-folder: './preview/${{ steps.extract_pr_number.pr_number }}'

      - if: github.event_name == 'pull_request' && github.event.pull_request.action == 'closed'
        run: mkdir empty-folder

      - name: Deploy to Preview Environment
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        if: github.event_name == 'pull_request' && github.event.pull_request.action == 'closed'
        with:
          branch: gh-pages
          folder: ./empty-folder
          target-folder: './preview/${{ steps.extract_pr_number.pr_number }}'
