name: Build and deploy to Github Pages

on:
  push:
    branches:
      - main
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Build
        run: |
          npm ci
          npm run export

      - name: Upload build output
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./out

  deploy_prod:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    needs: [build]
    concurrency: deploy_prod_concurrency_group
    steps:
      - uses: actions/checkout@v2

      - name: Download build output
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: ./out

      - name: Set up mutex
        uses: ben-z/gh-action-mutex@v1.0-alpha-3
        with:
          branch: mutex-gh-pages
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: ./out
          clean-exclude: previews/*

  deploy_preview:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: [build]
    steps:
      - uses: actions/checkout@v2

      - name: Download build output
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: ./out

      - name: Set up mutex
        uses: ben-z/gh-action-mutex@v1.0-alpha-3
        # Specify write permissions explicitly to make dependabot PRs happy:
        # https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-940182533
        permissions:
          contents: write
        with:
          branch: mutex-gh-pages
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Preview Environment
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: ./out
          target-folder: './previews/pr-${{ github.event.pull_request.number }}/${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}'

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            I'm deploying a preview of [${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}][compare].
            It will be ready in about a minute. [You can view it here][preview].

            [compare]: ${{ github.event.pull_request.head.repo.html_url }}/compare/${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}
            [preview]: ${{ github.event.pull_request.head.repo.homepage }}/previews/pr-${{ github.event.pull_request.number }}/${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}
