name: Build and deploy to Github Pages

on:
  push:
    branches:
      - main
  pull_request:

  workflow_dispatch:

concurrency: provision_concurrency_group-${{ github.event.pull_request.number || github.ref_name }}

env:
  # This is used during the build step (vite.config.js) to determine the base URL.
  # https://vitejs.dev/guide/static-deploy#github-pages
  DEPLOY_PATH: ${{ github.ref_name == 'main' && '/' || format('/previews/pr-{0}/{1}...{2}', github.event.pull_request.number, github.event.pull_request.base.sha, github.event.pull_request.head.sha) }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          npm ci
          npm run build

      - name: Upload build output
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: build-output
          path: ./dist

  deploy_prod:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    needs: [build]
    concurrency: deploy_prod_concurrency_group
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Download build output
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: build-output
          path: ./dist

      - name: Set up mutex
        uses: ben-z/gh-action-mutex@v1.0-alpha-3
        with:
          branch: mutex-gh-pages
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8 # v4.7.3
        with:
          branch: gh-pages
          folder: ./dist
          clean-exclude: previews/*

  deploy_preview:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: [build]
    # Specify write permissions explicitly to make dependabot PRs happy:
    # https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-940182533
    # This is okay in this job because we don't execute any external code (e.g. npm export).
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Download build output
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: build-output
          path: ./dist

      - name: Set up mutex
        uses: ben-z/gh-action-mutex@v1.0-alpha-3
        with:
          branch: mutex-gh-pages
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Preview Environment
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8 # v4.7.3
        with:
          branch: gh-pages
          folder: ./dist
          target-folder: '.${{ env.DEPLOY_PATH }}'

      - name: Create comment
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            I'm deploying a preview of [${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}][compare].
            It will be ready in about a minute. [You can view it here][preview].

            [compare]: ${{ github.event.pull_request.head.repo.html_url }}/compare/${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}
            [preview]: ${{ github.event.pull_request.head.repo.homepage }}${{ env.DEPLOY_PATH }}
